# fly.toml app configuration file generated for vernissage-server on 2023-05-29T17:36:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# Here https://fly.io/docs/reference/private-networking/#flycast-private-load-balancing we have information about private proxy.
#

app = "vernissage-server"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2